/* AUTO-GENERATED by export_nn.py -- do not edit.
 * run:    KAIST_V0_test14_lre-4
 * sensor: KAIST_V0_test  (superellipsoid)
 */
#ifndef KAIST_NET_H
#define KAIST_NET_H

#ifdef __cplusplus
extern "C" {
#endif

#define NN_N_TAXEL  8
#define NN_HISTORY  32
#define NN_IN_CHAN  256     /* NN_N_TAXEL * NN_HISTORY */
#define NN_X_MAX    2.514829844e+05f

/* ---------------------------------------------------------------------------
 * INPUT CONTRACT -- taken from the training source. Do not "fix" casually.
 *
 *   nn_push() takes 8 floats in sensor order s1..s8. They must be
 *   ForceSensor::raw_data[]  --  i.e.  (pressure - 100000).
 *   NOT the absolute MS5849 pressure.
 *   (offset_data[] happens to be identical today: Calibrate() is never
 *    called, so offsets[] stays zero. Use raw_data[] anyway -- it is the
 *    array that is actually transmitted and therefore actually trained on.)
 *
     Chain of custody for the training data:
       ForceSensor::Sample()      raw_data[i] = pressure - 100000
       pack_pressure_reply()      transmits raw_data[] over FDCAN
       gantry_control/raw_data/   .npy records exactly those values as s1..s8
       process_data_npy.py        writes data[:, s_i] straight through --
                                  calibration_offset is computed at ~line 352
                                  and then NEVER USED
       NewSensorDataset           X[:, i] = dataset[:, key[f's{i+1}']]; X / X_max
     So the tensor the net trained on IS raw_data[]. Feed it raw_data[].
 *
 *   Scaling is ONE global scalar (NewSensorDataset: X_max = abs(X_train).max()):
 *       in[i] = counts / NN_X_MAX
 *   Not per-channel. No mean subtraction.
 *
 *   Flatten order is TIME-MAJOR (FCNEncoder._encode: x.view(bs, -1) on
 *   (bs, history, 8)):
 *       [t0_s1..t0_s8, t1_s1..t1_s8, ...]      oldest sample first.
 * ------------------------------------------------------------------------- */

/* superellipsoid, read from decoder.normalize_u_params */
#define NN_SE_A   1.600000000e+01f
#define NN_SE_B   1.250000000e+01f
#define NN_SE_C   6.000000000e+00f
#define NN_SE_E1  1.000000000e+00f
#define NN_SE_E2  5.000000000e-01f

typedef struct {
    float contact_prob;   /* already a probability -- the head ends in Sigmoid */
    float F[3];           /* Fx, Fy, Fz   [N]                                  */
    float u[3];           /* contact position on the surface  [mm]             */
} nn_output_t;

void nn_reset(void);                       /* clear history; call after Initialize() */
void nn_push(const float *taxels);         /* one sample, s1..s8                    */
int  nn_infer(nn_output_t *out);           /* 0 until NN_HISTORY samples buffered   */
void nn_forward_raw(const float *in, nn_output_t *out);  /* pre-normalised input    */
int  nn_selftest(float *worst);            /* replay golden vectors vs PyTorch       */

#ifdef __cplusplus
}
#endif
#endif
